Upgrade django-parler.
Error was:

    ImportError: cannot import name ReverseSingleRelatedObjectDescriptor

SingleRelatedObjectDescriptor was renamed in Django 1.9.

Parler upgraded to support this and we need to upgrade here too.